### ISSUE TITLE
Generalize for building any rustdoc-generated documentation

### ISSUE THREAD

**Issue by tomjakubowski** [indirect/dash-rust#3]
Occurred to me today it wouldn't be that hard, and would be very useful, to be able to generate docsets from rustdoc documentation for an arbitrary Rust crate with this tool. I think they could all go in the `rust` `DocSetPlatformFamily` and it would just work very smoothly.

**Comment by bvssvni** [comment]
In the [Piston](http://www.piston.rs/) project we have a lot of documentation. I am testing Dash now for the first time, but it looks very decent. Any thoughts about using Dash for this?

**Comment by indirect** [comment]
@bvssvni Dash explicitly supports documentation for libraries, and has built-in support for generating docs for libraries in Ruby, Go, and other languages:

![libdocs](http://files.arko.net/image/2u3z3S2K2I3j/Image%202014-06-28%20at%209.11.50%20AM.png)

I think a Dash docset for Piston would be awesome, and if there's a way to make this repo friendlier for generating general docs, I would be interested in doing it.

**Comment by bvssvni** [comment]
Cool! Can we set up a checklist of what needs to be done? I would like to contribute, but don't know where to start.

**Comment by tomjakubowski** [comment]
In our case, it wouldn't be quite as slick as the screenshot @indirect showed; Cocoa, Ruby, Java, Scala, PHP, and Go have explicit support for package docsets in Dash, which makes use of their centralized package/documentation repositories.

For now the best we can hope for is generalizing `dash-rust` into a tool that makes new docsets from arbitrary source trees. A key question is the `DocSetPlatformFamily` entry in `Info.plist`; this determines how docsets are "grouped" together and their default search keyword. I guess they could just all go under `rust`.

**Comment by indirect** [comment]
To be the most like the current setup, I would suggest something like "rustlib". Ruby libraries have their own keyword, "rubygems".

**Comment by tomjakubowski** [comment]
Seems reasonable to me. People could override them too, for example a hypothetical Pison docset (which I imagine would cover many, many crates) could be `piston`.
